Cshe/default route fix
twang7310/rate-my-cse pull request #58
Opened 2023-11-06 23:10 UTC by ChengyuShe

Removed the "ratemycse" part from the URL and fixed an issue that caused the default URL to not display the blue background on the home page.

2023-11-06 23:25 UTC, twang7310 reviewed
I think .vercel folder was added to gitignore by Jeremy, so it shouldn't be pushed to main.
Do this on your branch please:

git fetch origin jnguyen/add-db
git merge

And then push again

2023-11-06 23:27 UTC, twang7310 requested changes
I think .vercel folder was added to gitignore by Jeremy, so it shouldn't be pushed to main.
Do this on your branch please:

git fetch origin jnguyen/add-db
git merge

And then push again

2023-11-07 18:42 UTC, thaowii commented on app/src/App/App.tsx
> +// import {GetDefaultRoute} from '../Helpers/utils';
Don't leave commented out code

2023-11-07 23:40 UTC, thaowii approved these changes

2023-11-07 23:42 UTC, thaowii requested changes
Remove .vercel then push

2023-11-09 00:20 UTC, celestinebuendia requested changes
Change the tests you are failing (in App.test.tsx, the routing tests) so that they no longer contain 'rate-my-cse/' as a prefix

2023-11-14 22:13 UTC, celestinebuendia requested changes
Remove the .vercel folder

2023-11-14 22:13 UTC, celestinebuendia commented on app/.vercel/README.txt
Delete this .vercel folder then commit

2023-11-15 22:23 UTC, celestinebuendia approved these changes
Approving because you changed the tests and Thao's review asks for you to remove .vercel.

2023-11-16 22:04 UTC, thaowii approved these changes

2023-11-16 22:06 UTC, twang7310 approved these changes

2023-11-16 22:07 UTC, merged